name: Dependency Updates

on:
  schedule:
    - cron: "0 0 * * 0"  # Run weekly on Sunday at midnight
  workflow_dispatch:     # Allow manual triggering

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for creating pull requests
      pull-requests: write  # Needed for creating pull requests

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install pip-tools
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools

    - name: Update Python dependencies
      run: |
        # Create requirements.in file from current requirements.txt
        grep -v "==" requirements.txt > requirements.in

        # Generate updated requirements.txt
        pip-compile --upgrade --output-file requirements.txt requirements.in

        # Remove generated requirements.in
        rm requirements.in

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: Update dependencies"
        title: "Update dependencies"
        body: |
          This PR updates project dependencies to their latest versions.

          Dependencies were automatically updated using pip-compile.

          Please review and test before merging.
        branch: dependency-updates
        delete-branch: true
